import type { QuestPreview } from './model.ts';

export function renderPreviewPage(preview: QuestPreview): string {
  const data = JSON.stringify(preview).replaceAll('<', '\\u003c');
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>QuestSpec Preview</title>
<style>
:root{color-scheme:dark;--bg:#11161d;--panel:#181f27;--panel2:#202933;--line:#354353;--muted:#8ea1b5;--text:#edf5fc;--cyan:#58d8d5;--cyan2:#1d8c91;--gold:#f0bd65;--danger:#ef7f82}
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--text)}button,input,select{font:inherit;color:inherit}button,select,input{background:#151c23;border:1px solid #425264;border-radius:5px}button{cursor:pointer}button:hover{border-color:var(--cyan);background:#24303a}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid var(--cyan);outline-offset:2px}
header{height:64px;display:flex;align-items:center;gap:14px;padding:10px 14px;border-bottom:1px solid var(--line);background:#161c23}.brand{display:flex;align-items:center;gap:10px;font-size:18px;font-weight:750;min-width:230px}.brand-mark{display:grid;place-items:center;width:34px;height:34px;border:1px solid var(--cyan2);color:var(--cyan);background:#10242a;border-radius:6px}.source{color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:1}.source strong{color:var(--text)}.locale{padding:7px 30px 7px 10px}.stats{display:flex;gap:8px}.stat{padding:4px 9px;border:1px solid #33414f;border-radius:12px;color:var(--muted);font-size:12px}.stat b{color:var(--text)}
.app{display:grid;grid-template-columns:280px minmax(420px,1fr) 340px;height:calc(100% - 64px)}aside,.details{background:var(--panel);min-width:0}.sidebar{border-right:1px solid var(--line);display:flex;flex-direction:column}.sidebar-head{padding:14px;border-bottom:1px solid var(--line)}h1,h2,h3,p{margin-top:0}.sidebar h1{font-size:15px;margin-bottom:10px}.search{width:100%;padding:8px 10px}.chapter-tree{padding:8px;overflow:auto}.group{margin:6px 0 12px}.group-title{padding:6px 7px;color:#9eb3c8;text-transform:uppercase;font-size:11px;font-weight:750;letter-spacing:.08em}.chapter{width:100%;display:flex;align-items:center;gap:9px;padding:8px;text-align:left;border-color:transparent;background:transparent}.chapter.selected{background:#2b3742;border-color:#8295a7}.chapter-icon,.entry-icon{display:grid;place-items:center;flex:none;width:29px;height:29px;border:1px solid #526171;background:linear-gradient(145deg,#273441,#141a20);color:var(--cyan);font-size:11px;font-weight:800}.chapter-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.empty{padding:20px;color:var(--muted);text-align:center}
.workspace{position:relative;min-width:0;background:#252e39;overflow:hidden}.workspace::before{content:"";position:absolute;inset:0;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:22px 22px;pointer-events:none}.toolbar{position:absolute;z-index:3;left:12px;right:12px;top:10px;display:flex;gap:8px;align-items:center}.toolbar input{width:min(360px,50%);padding:8px 10px;background:#121920e8}.chapter-heading{padding:7px 10px;background:#172029e8;border:1px solid #455567;border-radius:4px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.toolbar-spacer{flex:1}.tool{width:34px;height:34px}.canvas{position:absolute;inset:0;width:100%;height:100%;touch-action:none}.edge{stroke:#c9a7ad;stroke-width:7;opacity:.82;stroke-linecap:round}.edge.hidden{stroke-dasharray:4 8;opacity:.35}.node{cursor:pointer}.node .shape{fill:url(#nodeGradient);stroke:#e6edf3;stroke-width:2}.node.optional .shape{stroke:var(--gold);stroke-dasharray:5 4}.node.selected .shape{stroke:var(--cyan);stroke-width:4;filter:drop-shadow(0 0 8px #58d8d599)}.node text{fill:white;font-size:10px;font-weight:850;text-anchor:middle;dominant-baseline:middle;paint-order:stroke;stroke:#111a;stroke-width:3px}.node .icon-glyph{font-size:20px;stroke:none}.node .title{font-size:9px;font-weight:650;stroke:#111;stroke-width:2.5px}.zoom{position:absolute;right:14px;bottom:14px;z-index:4;display:flex;flex-direction:column;gap:5px}.zoom button{width:36px;height:36px;background:#172029e8}.legend{position:absolute;left:14px;bottom:14px;color:var(--muted);font-size:11px;background:#172029dd;padding:6px 9px;border:1px solid #3c4a59;border-radius:4px}
.details{border-left:1px solid var(--line);display:flex;flex-direction:column}.tabs{display:flex;border-bottom:1px solid var(--line)}.tab{flex:1;border:0;border-radius:0;padding:13px;background:transparent;color:var(--muted);border-bottom:2px solid transparent}.tab.active{color:var(--text);border-bottom-color:var(--cyan)}.detail-body{padding:18px;overflow:auto}.hero{display:flex;align-items:center;gap:12px;margin-bottom:16px}.hero .entry-icon{width:48px;height:48px;font-size:20px}.hero h2{font-size:18px;margin:0}.subtitle{color:var(--muted);margin-top:2px}.description{color:#cbd7e1;white-space:pre-line}.meta{display:grid;grid-template-columns:auto 1fr;gap:6px 12px;padding:11px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);font-size:12px}.meta dt{color:var(--muted)}.meta dd{margin:0;word-break:break-word}.section{margin-top:18px}.section h3{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.entry{display:flex;align-items:center;gap:10px;padding:8px;margin:6px 0;background:var(--panel2);border:1px solid #334250;border-radius:5px}.entry-copy{min-width:0}.entry-label{overflow-wrap:anywhere}.entry-type{font-size:11px;color:var(--muted)}.diagnostic{padding:10px;margin-bottom:8px;border-left:3px solid var(--gold);background:#292723}.diagnostic.error{border-color:var(--danger);background:#2a2024}.diagnostic small{color:var(--muted)}.placeholder{padding:50px 16px;text-align:center;color:var(--muted)}.badge{display:inline-block;padding:2px 7px;border-radius:10px;background:#263642;color:var(--cyan);font-size:11px}.mobile-toggle{display:none}
@media(max-width:1000px){.app{grid-template-columns:230px 1fr}.details{position:absolute;right:0;top:64px;bottom:0;width:min(380px,90vw);z-index:10;box-shadow:-12px 0 30px #0008;transform:translateX(100%);transition:transform .2s}.details.open{transform:none}.mobile-toggle{display:block}.stats{display:none}}
@media(max-width:700px){header{height:56px}.app{height:calc(100% - 56px);grid-template-columns:1fr}.sidebar{position:absolute;left:0;top:56px;bottom:0;width:280px;z-index:10;transform:translateX(-100%);transition:transform .2s;box-shadow:12px 0 30px #0008}.sidebar.open{transform:none}.brand{min-width:0}.source{display:none}.mobile-toggle{display:block}.workspace{grid-column:1}.details{top:56px}}
</style>
</head>
<body>
<header>
 <button class="mobile-toggle" id="menuButton" aria-label="Toggle chapters">☰</button>
 <div class="brand"><span class="brand-mark">Q</span><span>QuestSpec Preview</span></div>
 <div class="source"><strong id="bookName"></strong><br><span id="directory"></span></div>
 <select class="locale" id="localeSelect" aria-label="Locale"></select>
 <div class="stats" id="stats"></div>
 <button class="mobile-toggle" id="detailsButton" aria-label="Toggle details">ⓘ</button>
</header>
<div class="app">
 <aside class="sidebar" id="sidebar"><div class="sidebar-head"><h1>Quest Book</h1><input class="search" id="chapterSearch" type="search" placeholder="Search chapters…" aria-label="Search chapters"></div><nav class="chapter-tree" id="chapterTree"></nav></aside>
 <main class="workspace" id="workspace">
  <div class="toolbar"><input id="questSearch" type="search" placeholder="Search quests in this chapter…" aria-label="Search quests"><div class="chapter-heading" id="chapterHeading"></div><div class="toolbar-spacer"></div><button class="tool" id="fitButton" title="Fit graph">⌗</button></div>
  <svg class="canvas" id="canvas" role="group" aria-label="Quest dependency graph"><defs><linearGradient id="nodeGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#5c6268"/><stop offset=".52" stop-color="#30383f"/><stop offset="1" stop-color="#161c21"/></linearGradient></defs><g id="viewport"><g id="edges"></g><g id="nodes"></g></g></svg>
  <div class="legend">Authored dependency lines · gold outline: optional quest</div><div class="zoom"><button id="zoomIn" aria-label="Zoom in">＋</button><button id="zoomOut" aria-label="Zoom out">−</button></div>
 </main>
 <section class="details" id="details"><div class="tabs"><button class="tab active" data-tab="detail">Details</button><button class="tab" data-tab="diagnostics">Diagnostics <span class="badge" id="diagnosticCount"></span></button></div><div class="detail-body" id="detailBody"></div></section>
</div>
<script>const BOOK=${data};
const state={locale:BOOK.selectedLocale,chapterId:null,questId:null,tab:'detail',scale:1,tx:0,ty:0};
const $=id=>document.getElementById(id);const localeSelect=$('localeSelect'),tree=$('chapterTree'),canvas=$('canvas'),viewport=$('viewport'),edges=$('edges'),nodes=$('nodes');
const locale=()=>BOOK.locales[state.locale];const chapter=()=>locale().chapters.find(c=>c.id===state.chapterId);const quest=()=>chapter()?.quests.find(q=>q.id===state.questId);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function resourceName(id){return (id?.split(':').pop()||'quest').replaceAll(/[_-]+/g,' ').replace(/\\b\\w/g,c=>c.toUpperCase())}
const emojiRules=[[/log|wood|plank|tree|sapling/,'🌳'],[/ingot|nugget|metal|iron|gold|copper/,'▰'],[/sword|knife|blade/,'⚔'],[/pickaxe|hammer|wrench|tool/,'🔧'],[/food|bread|cake|apple|meat|fish|stew/,'🍖'],[/book|paper|map|scroll/,'📖'],[/train|rail|track/,'🚂'],[/magic|wand|staff|spell/,'✦'],[/armor|helmet|chestplate/,'🛡'],[/potion|bottle|fluid/,'⚗'],[/xp|experience/,'✧'],[/advancement/,'★'],[/kill|entity/,'☠'],[/checkmark/,'✓']];
function glyph(icon,type=''){const id=(icon||type||'quest').toLowerCase();for(const [re,g] of emojiRules)if(re.test(id))return g;const n=(icon?.split(':').pop()||type||'Q').split(/[_-]/).filter(Boolean);return n.slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'Q'}
function iconHtml(icon,type){return '<span class="entry-icon" title="'+esc(icon||type||'Quest')+'">'+esc(glyph(icon,type))+'</span>'}
function init(){for(const key of Object.keys(BOOK.locales)){const o=document.createElement('option');o.value=key;o.textContent=key.replace('_','-').toUpperCase();localeSelect.append(o)}localeSelect.value=state.locale;$('directory').textContent=BOOK.directory;$('bookName').textContent=BOOK.directory.split('/').filter(Boolean).at(-1)||'Quest Book';$('diagnosticCount').textContent=BOOK.diagnostics.length||'';selectInitial();renderAll()}
function selectInitial(){const chapters=locale().chapters;if(!chapters.some(c=>c.id===state.chapterId))state.chapterId=chapters[0]?.id??null;state.questId=null}
function renderAll(){renderStats();renderTree();renderGraph();renderPanel()}
function renderStats(){const ch=locale().chapters,qs=ch.flatMap(c=>c.quests),deps=qs.reduce((n,q)=>n+q.dependencies.length,0);$('stats').innerHTML=[['chapters',ch.length],['quests',qs.length],['links',deps]].map(([k,v])=>'<span class="stat"><b>'+v+'</b> '+k+'</span>').join('')}
function renderTree(){const query=$('chapterSearch').value.trim().toLowerCase();tree.innerHTML='';for(const group of locale().groups){const chapters=locale().chapters.filter(c=>(c.groupId??'__ungrouped')===group.id).filter(c=>!query||c.title.toLowerCase().includes(query)||c.filename.toLowerCase().includes(query));if(!chapters.length)continue;const box=document.createElement('div');box.className='group';box.innerHTML='<div class="group-title">'+esc(group.title)+'</div>';for(const c of chapters){const b=document.createElement('button');b.className='chapter'+(c.id===state.chapterId?' selected':'');b.innerHTML=iconHtml(c.icon,'chapter')+'<span class="chapter-name">'+esc(c.title)+'</span>';b.title=c.filename;b.onclick=()=>{state.chapterId=c.id;state.questId=null;state.scale=1;state.tx=state.ty=0;renderAll();if(innerWidth<700)$('sidebar').classList.remove('open')};box.append(b)}tree.append(box)}if(!tree.children.length)tree.innerHTML='<div class="empty">No matching chapters</div>'}
function shapeElement(q,cx,cy,r){const shape=(q.shape||'circle').toLowerCase();if(shape.includes('diamond'))return svg('polygon',{points:[cx+','+(cy-r),(cx+r)+','+cy,cx+','+(cy+r),(cx-r)+','+cy].join(' '),class:'shape'});if(shape.includes('square'))return svg('rect',{x:cx-r,y:cy-r,width:r*2,height:r*2,rx:shape.startsWith('r')?8:1,class:'shape'});const sides=shape.includes('octagon')?8:shape.includes('hexagon')?6:shape.includes('pentagon')?5:shape.includes('gear')?12:0;if(sides){const pts=[];for(let i=0;i<sides;i++){const a=-Math.PI/2+i*Math.PI*2/sides;const rr=shape.includes('gear')&&i%2?r*.78:r;pts.push((cx+Math.cos(a)*rr)+','+(cy+Math.sin(a)*rr))}return svg('polygon',{points:pts.join(' '),class:'shape'})}return svg('circle',{cx,cy,r,class:'shape'})}
function svg(tag,attrs){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,String(v));return el}
function renderGraph(){const c=chapter();$('chapterHeading').textContent=c?c.title:'No chapter';edges.innerHTML='';nodes.innerHTML='';if(!c)return;const query=$('questSearch').value.trim().toLowerCase();const positions=new Map(c.quests.map(q=>[q.id,{x:q.x*84,y:q.y*84}]));for(const q of c.quests){const end=positions.get(q.id);for(const dep of q.dependencies){const start=positions.get(dep);if(!start||!end||q.hideDependencyLines)continue;edges.append(svg('line',{x1:start.x,y1:start.y,x2:end.x,y2:end.y,class:'edge'+(q.hideDependencyLines?' hidden':'')}))}}for(const q of c.quests){const p=positions.get(q.id),r=Math.max(25,Math.min(48,28*q.size));const g=svg('g',{class:'node'+(q.optional?' optional':'')+(q.id===state.questId?' selected':'')+(query&&!q.title.toLowerCase().includes(query)?' filtered':''),tabindex:'0',role:'button','aria-label':q.title,transform:'translate(0 0)'});if(query&&!q.title.toLowerCase().includes(query))g.style.opacity='.16';g.append(shapeElement(q,p.x,p.y,r));const icon=svg('text',{x:p.x,y:p.y-3,class:'icon-glyph'});icon.textContent=glyph(q.icon,q.tasks[0]?.type);g.append(icon);const title=svg('text',{x:p.x,y:p.y+r+14,class:'title'});title.textContent=q.title.length>25?q.title.slice(0,23)+'…':q.title;g.append(title);g.onclick=()=>selectQuest(q.id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectQuest(q.id)}};nodes.append(g)}requestAnimationFrame(()=>{if(state.scale===1&&state.tx===0&&state.ty===0)fitGraph(true);else applyTransform()})}
function selectQuest(id){state.questId=id;state.tab='detail';renderGraph();renderPanel();if(innerWidth<1000)$('details').classList.add('open')}
function fitGraph(readable=false){const c=chapter(),rect=canvas.getBoundingClientRect();if(!c||!c.quests.length||!rect.width)return;const xs=c.quests.map(q=>q.x*84),ys=c.quests.map(q=>q.y*84),minX=Math.min(...xs)-70,maxX=Math.max(...xs)+70,minY=Math.min(...ys)-70,maxY=Math.max(...ys)+70;state.scale=Math.min(1.35,Math.max(readable?.42:.18,Math.min((rect.width-70)/(maxX-minX||1),(rect.height-110)/(maxY-minY||1))));state.tx=rect.width/2-(minX+maxX)/2*state.scale;state.ty=rect.height/2-(minY+maxY)/2*state.scale+20;applyTransform()}
function applyTransform(){viewport.setAttribute('transform','translate('+state.tx+' '+state.ty+') scale('+state.scale+')')}
function renderPanel(){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===state.tab));const body=$('detailBody');if(state.tab==='diagnostics'){body.innerHTML=BOOK.diagnostics.length?BOOK.diagnostics.map(d=>'<div class="diagnostic '+d.severity+'"><strong>'+esc(d.severity.toUpperCase())+'</strong><div>'+esc(d.message)+'</div>'+(d.file?'<small>'+esc(d.file)+'</small>':'')+'</div>').join(''):'<div class="placeholder">No diagnostics. All readable preview structures loaded cleanly.</div>';return}const q=quest();if(!q){body.innerHTML='<div class="placeholder">Select a quest node to inspect its localized title, description, authored position, dependencies, tasks, and rewards.</div>';return}const entry=(e,kind)=>'<div class="entry">'+iconHtml(e.icon,e.type)+'<div class="entry-copy"><div class="entry-label">'+esc(e.label)+(e.count&&e.count!==1?' × '+e.count:'')+'</div><div class="entry-type">'+esc(kind+' · '+e.type)+(e.icon?' · '+esc(e.icon):'')+'</div></div></div>';body.innerHTML='<div class="hero">'+iconHtml(q.icon,q.tasks[0]?.type)+'<div><h2>'+esc(q.title)+'</h2>'+(q.subtitle?'<div class="subtitle">'+esc(q.subtitle)+'</div>':'')+'</div></div>'+(q.description.length?'<p class="description">'+q.description.map(esc).join('\\n\\n')+'</p>':'')+'<dl class="meta"><dt>Position</dt><dd>'+q.x+', '+q.y+'</dd><dt>Shape</dt><dd>'+esc(q.shape)+(q.optional?' · optional':'')+'</dd><dt>Dependencies</dt><dd>'+(q.dependencies.length?q.dependencies.map(id=>{const found=chapter().quests.find(x=>x.id===id);return esc(found?.title??id)}).join('<br>'):'None')+'</dd><dt>Physical ID</dt><dd>'+esc(q.id)+'</dd></dl>'+(q.tasks.length?'<div class="section"><h3>Tasks · '+q.tasks.length+'</h3>'+q.tasks.map(e=>entry(e,'Task')).join('')+'</div>':'')+(q.rewards.length?'<div class="section"><h3>Rewards · '+q.rewards.length+'</h3>'+q.rewards.map(e=>entry(e,'Reward')).join('')+'</div>':'')}
localeSelect.onchange=()=>{state.locale=localeSelect.value;selectInitial();state.scale=1;state.tx=state.ty=0;renderAll()};$('chapterSearch').oninput=renderTree;$('questSearch').oninput=renderGraph;$('fitButton').onclick=fitGraph;$('zoomIn').onclick=()=>{state.scale=Math.min(3,state.scale*1.22);applyTransform()};$('zoomOut').onclick=()=>{state.scale=Math.max(.12,state.scale/1.22);applyTransform()};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{state.tab=t.dataset.tab;renderPanel()});$('menuButton').onclick=()=>$('sidebar').classList.toggle('open');$('detailsButton').onclick=()=>$('details').classList.toggle('open');
let drag=null;canvas.addEventListener('pointerdown',e=>{if(e.target.closest('.node'))return;drag={x:e.clientX,y:e.clientY,tx:state.tx,ty:state.ty};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;state.tx=drag.tx+e.clientX-drag.x;state.ty=drag.ty+e.clientY-drag.y;applyTransform()});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();const rect=canvas.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top,old=state.scale,next=Math.max(.12,Math.min(3,old*(e.deltaY<0?1.12:.89)));state.tx=mx-(mx-state.tx)*next/old;state.ty=my-(my-state.ty)*next/old;state.scale=next;applyTransform()},{passive:false});addEventListener('resize',fitGraph);init();
</script>
</body></html>`;
}
