import type { Questbook } from '../../src/ir/questbook.ts';

const questbook: Questbook = {
  chapters: [
    {
      defaultHideDependencyLines: false,
      defaultQuestShape: '',
      filename: '01_foundations',
      group: 'industry',
      icon: { components: {}, id: 'minecraft:iron_pickaxe' },
      key: 'foundations',
      localKey: 'foundations',
      progressionMode: 'default',
      quests: [
        {
          dependencies: [],
          dependencyControlPoints: {},
          description: { en_us: ['Start here.'], ko_kr: ['여기서 시작하세요.'] },
          hideDependencyLines: false,
          hideUntilDependenciesVisible: false,
          key: 'foundations.start',
          localKey: 'start',
          optional: false,
          rewards: [],
          shape: '',
          size: 1,
          tasks: [
            {
              count: 1,
              disableToast: false,
              item: { components: {}, id: 'minecraft:oak_log' },
              key: 'foundations.start.log',
              localKey: 'log',
              matchComponents: 'none',
              optional: false,
              tags: [],
              taskScreenOnly: false,
              title: {},
              type: 'item',
            },
          ],
          title: { en_us: 'Start', ko_kr: '시작' },
          x: 0,
          y: 0,
        },
        {
          dependencies: ['foundations.start'],
          dependencyControlPoints: {},
          description: {},
          hideDependencyLines: false,
          hideUntilDependenciesVisible: false,
          key: 'foundations.finish',
          localKey: 'finish',
          optional: false,
          rewards: [
            {
              autoClaim: 'default',
              disableRewardScreenBlur: false,
              excludeFromClaimAll: false,
              ignoreRewardBlocking: false,
              key: 'foundations.finish.experience',
              localKey: 'experience',
              tags: [],
              teamReward: 'default',
              title: {},
              type: 'xp',
              xp: 100,
            },
          ],
          shape: '',
          size: 1,
          tasks: [
            {
              advancement: 'minecraft:story/root',
              criterion: '',
              disableToast: false,
              key: 'foundations.finish.root',
              localKey: 'root',
              optional: false,
              tags: [],
              title: {},
              type: 'advancement',
            },
          ],
          title: { en_us: 'Finish', ko_kr: '완료' },
          x: 3,
          y: 0,
        },
      ],
      title: { en_us: 'Foundations', ko_kr: '기초' },
    },
  ],
  defaultLocale: 'en_us',
  groups: [{ key: 'industry', title: {} }],
  locales: ['en_us', 'ko_kr'],
  rewardTables: [],
  settings: {},
  target: {
    dataVersion: 13,
    loader: 'neoforge@21.1.248',
    minecraft: '1.21.1',
    questSystem: 'ftbquests@2101.1.33',
    serializer: 'ftblibrary@2101.1.35',
  },
};

export function createQuestbookFixture(): Questbook {
  return structuredClone(questbook);
}
